import Head from 'next/head'
import Brand from './brand'
import { Box, Typography } from '@mui/material'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>


        <Box sx={{display:'flex', flexDirection:'column', justifyContent:'center'}}>
            <Typography sx={{textAlign:"center", color:'white'}} variant="h1" >Welcome</Typography>
            <Link style={{color:'white', textAlign:'center'}} href={'/dashboard'}>Dashboard</Link>
        </Box>

      </main>
    </>
  )
}
